import "./globals.css";
import Nav1 from "../components/nav1";
import Nav2 from "../components/nav2";
import Footer from "@/components/footer";
export const metadata = {
  title: "Restaurant Reservation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav1/>
        <Nav2/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
